# Generated by Django 3.2.4 on 2021-06-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("price", models.PositiveIntegerField(default=0)),
                ("discount_rate", models.FloatField(default=0)),
            ],
        ),
    ]
